#!/usr/bin/env python3
"""wiki_build.py -- directory init, indexing, search, and health-check for a
personal wiki.

Design constraint: uses only the Python standard library (json / re / pathlib /
argparse), with no third-party packages, so it runs on a bare environment.

Wiki directory structure (created by the init subcommand)::

    <dir>/
      raw/          source material: clippings, originals, PDF-extracted text;
                    in-only, never edited
      notes/        compiled notes: what you write, with [[wiki links]] and #tags
      index.json    sharded index: generated by the index subcommand; do not edit by hand

Subcommands:
  init    <dir>                 initialize the directory skeleton
  index   <dir>                 scan raw/ and notes/ to rebuild index.json
  search  <dir> "keyword"       weighted search over the index
  lint    <dir>                 orphan-note / broken-link / empty-note checks
  stats   <dir>                 totals and structure statistics

Conventions (the core contract of this skill; both index and lint rely on them):
  - Note title: the first H1 (`# Title`); if no H1, fall back to the filename (without extension).
  - Tags: `#tag` form in the body, English or CJK; a `#` immediately followed by a
    digit is not a tag (to avoid "#1").
  - Links: `[[target]]` or `[[target|display text]]`; the target resolves against two
    aliases -- "filename" and "H1 title".
  - Files under raw/ are only indexed and searched; they do not participate in lint's orphan detection.
"""

import argparse
import json
import re
import sys
import unicodedata
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------- Constants and regex

RAW_DIR = "raw"
NOTES_DIR = "notes"
INDEX_FILE = "index.json"
MARKDOWN_SUFFIXES = {".md", ".markdown", ".txt"}

H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
# Tags: `#` followed by a letter / CJK char / underscore, then allowing digits.
# (?<![\w#]) avoids mistaking URL fragments (a#b) and `##headings` for tags.
TAG_RE = re.compile(r"(?<![\w#])#([A-Za-z_][\w\u4e00-\u9fff-]*|[\u4e00-\u9fff][\w\u4e00-\u9fff-]*)")
WIKILINK_RE = re.compile(r"\[\[([^\[\]|]+?)(?:\|([^\[\]]*))?\]\]")
# CJK counted by character, English by word -- only used as a rough length estimate
CJK_RE = re.compile(r"[\u4e00-\u9fff]")
WORD_RE = re.compile(r"[A-Za-z0-9]+")

# Search weights: title hit > tag hit > body hit
W_TITLE, W_TAG, W_BODY = 10, 5, 1


class WikiError(Exception):
    """User-facing error: its message is caught by main and printed as an ERROR line."""


# ---------------------------------------------------------------- Utilities


def die(msg: str, code: int = 1):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(code)


def count_words(text: str) -> int:
    """CJK by character, English by word, giving a cross-language comparable length count."""
    return len(CJK_RE.findall(text)) + len(WORD_RE.findall(text))


def display_width(s: str) -> int:
    """Terminal display width: CJK full-width chars take 2 columns, others 1.

    Aligning by len() directly makes a full-width CJK string and a Latin string like
    "infra" misalign in a monospace font, which is especially visible when mixing
    CJK and English labels in the stats table.
    """
    return sum(2 if unicodedata.east_asian_width(c) in "WF" else 1 for c in s)


def pad(s: str, width: int) -> str:
    """Pad on the right with spaces by display width."""
    return s + " " * max(0, width - display_width(s))


def read_text(path: Path) -> str:
    """Tolerant read: a broken encoding must not take down the whole index."""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        raise WikiError(f"cannot read {path}: {e}")


def require_wiki(root: Path) -> Path:
    """Confirm the root is an initialized wiki; return its absolute path."""
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise WikiError(f"directory does not exist: {root} (run init first)")
    if not (root / NOTES_DIR).is_dir():
        raise WikiError(f"no {NOTES_DIR}/ under {root}; not a wiki directory (run init first)")
    return root


def iter_pages(root: Path):
    """Yield (bucket, path); bucket in {raw, notes}. Skip hidden files and .git."""
    for bucket in (RAW_DIR, NOTES_DIR):
        base = root / bucket
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*")):
            if not p.is_file():
                continue
            if any(part.startswith(".") for part in p.relative_to(root).parts):
                continue
            if p.suffix.lower() not in MARKDOWN_SUFFIXES:
                continue
            yield bucket, p


def parse_page(root: Path, bucket: str, path: Path) -> dict:
    """Parse one Markdown page into the fields the index needs."""
    text = read_text(path)
    rel = path.relative_to(root).as_posix()

    m = H1_RE.search(text)
    title = m.group(1).strip() if m else path.stem
    body = text
    if m:
        # exclude the title line itself from body hits, or title words get counted twice
        body = text[: m.start()] + text[m.end():]

    # deduplicate while preserving order: the same tag appearing multiple times in one note counts once
    tags, seen = [], set()
    for t in TAG_RE.findall(text):
        if t not in seen:
            seen.add(t)
            tags.append(t)

    links, seen_l = [], set()
    for target, alias in WIKILINK_RE.findall(text):
        target = target.strip()
        key = target.lower()
        if target and key not in seen_l:
            seen_l.add(key)
            links.append(
                {"target": target, "alias": (alias or "").strip() or None}
            )

    return {
        "path": rel,
        "bucket": bucket,
        "slug": path.stem,
        "title": title,
        "tags": tags,
        "links": links,
        "words": count_words(text),
        "lines": len(text.splitlines()),
        "empty": not text.strip() or count_words(text) < 5,
    }


# ---------------------------------------------------------------- Index building


def build_index(root: Path) -> dict:
    """Scan raw/ and notes/ and produce the full index dict."""
    pages = [parse_page(root, b, p) for b, p in iter_pages(root)]

    # Alias table for resolving links: both slug (filename) and title (H1) count,
    # priority slug > title
    by_slug: dict[str, str] = {}
    by_title: dict[str, str] = {}
    for pg in pages:
        by_slug.setdefault(pg["slug"].lower(), pg["path"])
        by_title.setdefault(pg["title"].lower(), pg["path"])

    backlinks: dict[str, list] = defaultdict(list)
    unresolved: list[dict] = []
    for pg in pages:
        for lk in pg["links"]:
            tgt = lk["target"].lower()
            dest = by_slug.get(tgt) or by_title.get(tgt)
            if dest:
                backlinks[dest].append(pg["path"])
            else:
                unresolved.append({"from": pg["path"], "target": lk["target"]})

    for pg in pages:
        pg["backlinks"] = sorted(set(backlinks.get(pg["path"], [])))
        # whether an outlink resolves is left to lint; here we only record the count
        pg["outlinks"] = len(pg["links"])

    return {
        "schema": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "root_name": root.name,
        "count": len(pages),
        "pages": pages,
        "unresolved_links": unresolved,
    }


def save_index(root: Path, index: dict):
    (root / INDEX_FILE).write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def load_index(root: Path) -> dict:
    f = root / INDEX_FILE
    if not f.is_file():
        raise WikiError(f"index does not exist: {f} (run index first)")
    try:
        return json.loads(f.read_text(encoding="utf-8"))
    except ValueError as e:
        raise WikiError(f"index corrupted ({e}): delete {INDEX_FILE} and rerun index")


# ---------------------------------------------------------------- Subcommands


def cmd_init(args) -> int:
    root = Path(args.dir).expanduser().resolve()
    if root.exists() and any(root.iterdir()) and not args.force:
        # no destructive overwrite: a non-empty directory requires explicit --force
        raise WikiError(f"directory is not empty: {root}; add --force to confirm initialization")

    for sub in (RAW_DIR, NOTES_DIR):
        (root / sub).mkdir(parents=True, exist_ok=True)
        # .gitkeep lets an empty directory be tracked by git
        keep = root / sub / ".gitkeep"
        keep.touch(exist_ok=True)

    readme = root / "README.md"
    if not readme.exists():
        readme.write_text(
            f"# {root.name} -- personal knowledge base\n\n"
            f"- `{RAW_DIR}/` source material (clippings, originals), in-only\n"
            f"- `{NOTES_DIR}/` compiled notes, interlinked with [[wiki links]], categorized with #tags\n\n"
            "Rebuild the index: `python3 wiki_build.py index .`\n",
            encoding="utf-8",
        )

    idx = root / INDEX_FILE
    if not idx.exists():
        save_index(root, build_index(root))

    print(f"initialized: {root}")
    print(f"  {RAW_DIR}/  {NOTES_DIR}/  {INDEX_FILE}  README.md")
    return 0


def cmd_index(args) -> int:
    root = require_wiki(Path(args.dir))
    index = build_index(root)
    save_index(root, index)

    notes = [p for p in index["pages"] if p["bucket"] == NOTES_DIR]
    raw = [p for p in index["pages"] if p["bucket"] == RAW_DIR]
    tags = sorted({t for p in index["pages"] for t in p["tags"]})

    print(f"indexed: {root / INDEX_FILE}")
    print(f"  pages  : {index['count']}  (notes {len(notes)} / raw {len(raw)})")
    print(f"  tags   : {len(tags)}")
    print(f"  links  : resolved "
          f"{sum(len(p['backlinks']) for p in index['pages'])}, "
          f"unresolved {len(index['unresolved_links'])}")
    for p in index["pages"]:
        print(f"    - [{p['bucket']}] {p['title']} "
              f"({p['words']}w, {len(p['tags'])} tags, {p['outlinks']} out)")
    return 0


def cmd_search(args) -> int:
    root = require_wiki(Path(args.dir))
    index = load_index(root)
    query = args.keyword.strip().lower()
    if not query:
        raise WikiError("keyword is empty")

    results = []
    for pg in index["pages"]:
        title_l = pg["title"].lower()
        tags_l = [t.lower() for t in pg["tags"]]
        # body hit: re-read from disk, so the index need not store the full text to be searchable
        body_l = read_text(root / pg["path"]).lower()

        score, why = 0, []
        if query in title_l:
            score += W_TITLE * title_l.count(query)
            why.append("title")
        if any(query in t for t in tags_l):
            score += W_TAG * sum(1 for t in tags_l if query in t)
            why.append("tag")
        n_body = body_l.count(query)
        if n_body:
            score += W_BODY * n_body
            why.append("body")
        if score:
            results.append((score, pg, why, n_body))

    results.sort(key=lambda r: (-r[0], r[1]["path"]))
    limit = args.limit or 20

    print(f'search "{args.keyword}" in {root.name}: {len(results)} hit(s)')
    if not results:
        print("  (no hits; try another keyword, or run index first to confirm material is ingested)")
        return 0
    for score, pg, why, n_body in results[:limit]:
        bits = ", ".join(
            f"title×{pg['title'].lower().count(query)}" if w == "title"
            else f"tag" if w == "tag"
            else f"body×{n_body}"
            for w in why
        )
        print(f"  {score:>4}  [{pg['bucket']}] {pg['title']}")
        print(f"        {pg['path']}  ({bits})")
    if len(results) > limit:
        print(f"  ... and {len(results) - limit} more; adjust with --limit")
    return 0


def cmd_lint(args) -> int:
    root = require_wiki(Path(args.dir))
    index = load_index(root)

    orphans, broken, empties, tagged = [], [], [], []
    for pg in index["pages"]:
        if pg["bucket"] != NOTES_DIR:
            continue
        if pg["empty"]:
            empties.append(pg)
        if not pg["backlinks"]:
            orphans.append(pg)
        if not pg["tags"]:
            tagged.append(pg)

    # Broken links: the outlinks whose target could not be resolved (already computed in
    # the index; here grouped by source)
    by_source = defaultdict(list)
    for u in index["unresolved_links"]:
        by_source[u["from"]].append(u["target"])

    print(f"lint {root.name}: "
          f"{len(orphans)} orphan(s), {len(by_source)} page(s) with broken link(s), "
          f"{len(empties)} empty")
    print()

    print("[orphan notes] no inbound links; neither searchable nor navigable")
    for pg in orphans or []:
        print(f"  - {pg['path']}  ({pg['title']})")
    if not orphans:
        print("  (none)")
    print()

    print("[broken links] link points to a page that does not exist")
    for src, targets in sorted(by_source.items()):
        print(f"  - {src}")
        for t in targets:
            print(f"      -> [[{t}]] not found")
    if not by_source:
        print("  (none)")
    print()

    print("[empty notes] body under 5 words, usually placeholders")
    for pg in empties or []:
        print(f"  - {pg['path']}")
    if not empties:
        print("  (none)")
    print()

    if tagged:
        print(f"[hint] {len(tagged)} notes have no tags (not an error, but weakens search)")
        for pg in tagged[:5]:
            print(f"  - {pg['path']}")
        if len(tagged) > 5:
            print(f"  ... and {len(tagged) - 5} more")

    return 1 if (orphans or by_source or empties) else 0


def cmd_stats(args) -> int:
    root = require_wiki(Path(args.dir))
    index = load_index(root)

    notes = [p for p in index["pages"] if p["bucket"] == NOTES_DIR]
    raw = [p for p in index["pages"] if p["bucket"] == RAW_DIR]
    all_pages = index["pages"]

    total_words = sum(p["words"] for p in all_pages)
    tag_counter = Counter(t for p in all_pages for t in p["tags"])
    # average link count = outlinks + inlinks, so island pages stand out
    link_counts = [p["outlinks"] + len(p["backlinks"]) for p in notes]
    avg_links = (sum(link_counts) / len(link_counts)) if link_counts else 0.0

    print(f"stats: {root.name}")
    print(f"  notes          : {len(notes)}")
    print(f"  raw            : {len(raw)}")
    print(f"  total words    : {total_words}")
    print(f"  avg words/note : {total_words / len(all_pages):.0f}" if all_pages else "  avg words/note : 0")
    print(f"  avg links/note : {avg_links:.2f}  (out+in links)")
    print(f"  distinct tags  : {len(tag_counter)}")
    print(f"  generated_at   : {index.get('generated_at', '?')}")
    print()

    print("  [tag distribution] top 10")
    if tag_counter:
        top = tag_counter.most_common(10)
        width = max(display_width(t) for t, _ in top)
        for tag, n in top:
            bar = "█" * min(n, 30)
            print(f"    {pad(tag, width)}  {n:>3}  {bar}")
    else:
        print("    (no tags; use #tags to categorize notes)")

    if notes:
        top = sorted(notes, key=lambda p: -p["outlinks"])[:5]
        print()
        print("  [most outlinks] top 5")
        for p in top:
            print(f"    {p['outlinks']:>3}  {p['path']}")

    if index["unresolved_links"]:
        print()
        print(f"  [warning] {len(index['unresolved_links'])} broken link(s); "
              f"run lint for details")
    return 0


# ---------------------------------------------------------------- Entrypoint


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="wiki_build.py",
        description="Personal knowledge-base builder: init / index / search / lint / stats (pure stdlib)",
        epilog="example: python3 wiki_build.py init mywiki && "
               "python3 wiki_build.py index mywiki",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("init", help="initialize the wiki directory structure")
    s.add_argument("dir", help="wiki root directory (created if missing)")
    s.add_argument("--force", action="store_true", help="proceed even if the target directory is non-empty")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("index", help="scan raw/ and notes/ to rebuild index.json")
    s.add_argument("dir")
    s.set_defaults(func=cmd_index)

    s = sub.add_parser("search", help="search the index (title > tag > body)")
    s.add_argument("dir")
    s.add_argument("keyword")
    s.add_argument("--limit", type=int, default=20, help="max rows to show (default 20)")
    s.set_defaults(func=cmd_search)

    s = sub.add_parser("lint", help="check orphans / broken links / empty notes (exit code 1 if findings)")
    s.add_argument("dir")
    s.set_defaults(func=cmd_lint)

    s = sub.add_parser("stats", help="print totals, tag distribution, and link density")
    s.add_argument("dir")
    s.set_defaults(func=cmd_stats)

    args = p.parse_args(argv)
    try:
        return args.func(args)
    except WikiError as e:
        die(str(e))
    except KeyboardInterrupt:
        print("\ninterrupted", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
