#!/usr/bin/env python3
"""
gen_report.py — pull this week's (or the last N days') work from git log +
git diff --stat and emit a weekly-report Markdown with fixed sections
(what got done / blockers / next week's plan).

Hard rules:
- default dry-run prints a preview, writes nothing
- --write writes the file (to a new file)
- no credentials / no network (pure local git + filesystem)
- do not touch git remotes, do not push
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys

TEMPLATE = """# Weekly report · {start} ~ {end}

> Generated: {today} · Project: {repo} · Author: {author}

## 1. Done this week

{done}

## 2. Blockers / risks

{blockers}

## 3. Plan for next week

{next}

---
*Generated by weekly-report-generator; "blockers" and "next week" are placeholders by default and need human fill-in.*
"""


def sh(args: list[str], cwd: str) -> str:
    try:
        return subprocess.check_output(args, cwd=cwd, text=True, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def git_commits_since(days: int, cwd: str) -> list[str]:
    """List commit subjects on the current branch for the last N days (no full history)."""
    out = sh(["git", "log", f"--since={days} days ago", "--pretty=%ad | %s | %an",
              "--date=short", "--no-merges"], cwd)
    lines = []
    for raw in out.splitlines():
        parts = raw.split(" | ")
        if len(parts) >= 3:
            lines.append(f"{parts[0]} {parts[2]}: {parts[1]}")
    return lines


def diff_stat(cwd: str) -> dict:
    """Rough --stat line changes between the last merge-base..HEAD (approximated as HEAD~3..HEAD)."""
    out = sh(["git", "diff", "--stat", "HEAD~3", "HEAD"], cwd)
    return {"raw": out.strip() or "(no diff stat)"}


def group_by_day(commits: list[str]) -> dict:
    by_day = {}
    for c in commits:
        day = c[:10]
        by_day.setdefault(day, []).append(c)
    return by_day


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a weekly report from git log (offline, dry-run by default)")
    ap.add_argument("--days", type=int, default=7, help="look-back window in days (default 7)")
    ap.add_argument("--repo", default=".", help="git repo path (default: cwd)")
    ap.add_argument("--author", default="agent", help="author name in report")
    ap.add_argument("--blockers", default="[fill in: this week's blockers]", help="free-text blockers")
    ap.add_argument("--next", default="[fill in: next week's plan]", help="free-text plan for next week")
    ap.add_argument("--input", default="", help="optional JSON with {done, blockers, next}")
    ap.add_argument("-o", "--out", default="weekly-report.md")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    if not os.path.isdir(os.path.join(args.repo, ".git")):
        print(f"[ERROR] {args.repo} is not a git repo", file=sys.stderr)
        return 2

    start = (datetime.date.today() - datetime.timedelta(days=args.days)).isoformat()
    end = datetime.date.today().isoformat()

    commits = git_commits_since(args.days, args.repo)
    grouped = group_by_day(commits)
    stat = diff_stat(args.repo)

    # human-provided JSON has the highest priority
    done_blocks: list[str] = []
    blockers = args.blockers
    next_plan = args.next
    if args.input:
        try:
            with open(args.input, "r", encoding="utf-8") as f:
                data = json.load(f)
            done_blocks = data.get("done", [])
            blockers = data.get("blockers", blockers)
            next_plan = data.get("next", next_plan)
        except Exception as e:
            print(f"[WARN] --input failed ({e}); using git-derived", file=sys.stderr)

    if not done_blocks:
        done_blocks = [f"- [{d}] {c}" for d, cs in grouped.items() for c in cs] or ["(no commits this week)"]

    doc = TEMPLATE.format(
        start=start, end=end,
        today=datetime.date.today().isoformat(),
        repo=os.path.basename(os.path.abspath(args.repo)),
        author=args.author,
        done="\n".join(done_blocks),
        blockers=blockers,
        next=next_plan,
    )

    print(doc)
    print(f"--- stats: {len(commits)} commits, {len(grouped)} active days ---")
    print(f"[DRY-RUN] git stat: {stat['raw'][:120]}{'…' if len(stat['raw']) > 120 else ''}")

    if args.write:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(doc)
        print(f"[WRITE] {args.out}")
    else:
        print(f"[DRY-RUN] nothing written. Re-run with --write -o {args.out!r}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
