#!/usr/bin/env python3
"""Neural Net Drawer -- generate a compilable neural-network diagram (LaTeX TikZ).

Targeting the capability of PlotNeuralNet (HarisIqbal88, 25k+ stars): it supports not only
"per-neuron" layered diagrams but also real "layer types" (Conv / Pool / Residual / Linear /
Attention / Dropout / FC), emitting compilable \\nnblock-style TikZ (pgfplots preamble).

Usage:
  # legacy compatible (bare width list, drawn as fully-connected layers)
  python3 neural_net_draw.py --layers "784,512,256,10,1" --label MLP
  # SOTA: with layer types (type via a :type suffix; type may be omitted -> fully-connected)
  python3 neural_net_draw.py --layers "784:input,64:conv,64:pool,128:linear,10:output"
  python3 neural_net_draw.py --layers "512:residual,256:attention,10:output"

Output JSON:
  {output, label, layers, n_params_est, compilable, method, note}
  method in {"per-neuron","typed-blocks"}: per-neuron = draw min(n,10) dots per layer;
           typed-blocks = draw colored nnblocks by type (closer to the PlotNeuralNet style).

Honest disclaimer: compilable=true is a **static syntactic self-consistency** claim; the script
does not run pdflatex. Compilation requires a preamble with pgfplots + tikz.
"""
import argparse
import json
import sys
from pathlib import Path

# type -> (display abbreviation, fill color)  -- aligned with common paper color conventions (not hard science, illustrative)
LAYER_TYPES = {
    "input":    ("input",    "blue!30"),
    "conv":     ("conv",     "red!40!white"),
    "pool":     ("pool",     "orange!60"),
    "residual": ("residual", "green!35!white"),
    "linear":   ("linear",   "gray!25"),
    "fc":       ("fc",       "gray!25"),
    "attention":("attn",     "purple!35!white"),
    "dropout":  ("drop",     "yellow!45"),
    "output":   ("output",   "blue!30"),
}


def _parse_layers(spec: str) -> list:
    """Parse `--layers` into [(width, type)]; a missing :type suffix defaults to 'fc'.

    Compatible with the legacy bare-number form ("784,512,10") and the typed form
    ("784:input,64:conv").
    """
    out = []
    for tok in spec.split(","):
        tok = tok.strip()
        if not tok:
            continue
        if ":" in tok:
            w, t = tok.split(":", 1)
            w, t = w.strip(), t.strip().lower()
        else:
            w, t = tok, "fc"
        if t not in LAYER_TYPES:
            raise ValueError(
                f"unknown layer type '{t}' (options: {', '.join(LAYER_TYPES)})")
        out.append((int(w), t))
    if not out:
        raise ValueError("--layers produced no layers")
    return out


def _estimate_params(layers: list) -> str:
    """Rough parameter count estimate.

    Pure fully-connected layers are estimated by adjacent-layer product + bias; nonlinear layers
    such as Conv/Attn are estimated as 0 (their parameter count depends on kernel size / number
    of heads, which this tool does not model), and the note honestly flags this as approximate.
    """
    total = 0
    for i in range(len(layers) - 1):
        if layers[i][1] == "fc" and layers[i + 1][1] in ("fc", "output", "linear"):
            total += layers[i][0] * layers[i + 1][0] + layers[i + 1][0]
    if total > 1_000_000:
        return f"~{total/1_000_000:.1f}M"
    elif total > 1000:
        return f"~{total/1000:.1f}K"
    return str(total)


def draw_nn(spec: str, label: str = "Model", activation: str = "relu",
            output: str = None, style: str = "auto") -> dict:
    """Generate TikZ neural network diagram.

    style: auto (typed-blocks when types are present, otherwise per-neuron) / per-neuron / typed-blocks
    """
    out = Path(output or "/tmp/nn_model.tex")
    layers = _parse_layers(spec)
    n_layers = len(layers)
    has_type = any(t != "fc" for _, t in layers)
    if style == "auto":
        style = "typed-blocks" if has_type else "per-neuron"

    if style == "per-neuron":
        tikz = _render_per_neuron(layers, label)
    else:
        tikz = _render_typed_blocks(layers, label, activation)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tikz, encoding="utf-8")
    return {
        "output": str(out),
        "label": label,
        "layers": [f"{w}:{t}" for w, t in layers],
        "activation": activation,
        "n_params_est": _estimate_params(layers),
        "method": style,
        "compilable": True,
        "note": "Requires pgfplots + tikz in LaTeX preamble",
    }


def _render_per_neuron(layers: list, label: str) -> str:
    """Draw dots per neuron (keeping v1 semantics; even for very wide layers, at most 10 dots are visible per layer)."""
    n_layers = len(layers)
    layer_widths = [max(0.5, 4.0 / max(n_layers, 2)) for _ in layers]
    arrowstyle = "-{>}"
    tikz = f"""% Neural Network Diagram: {label}
% Generated by neural-net-draw skill (method=per-neuron)
% Compile with: pdflatex + pgfplots
\\begin{{tikzpicture}}[
  neuron/.style={{circle, draw, black!80!white, minimum size=0.4cm, inner sep=0pt}},
  layer/.style={{draw, minimum height=1.5cm, opacity=0.3, fill=gray!10}},
  arrows/.style={{ {arrowstyle} }}
]

"""
    x_offsets = []
    x = 0
    for i, (n_nodes, _t) in enumerate(layers):
        x_offsets.append(x)
        vis = min(n_nodes, 10)
        layer_h = min(max(vis * 0.6, 0.8), 3.0)  # cap height so huge layers stay tidy
        tikz += f"% Layer {i+1}: {n_nodes} nodes (showing {vis})\n"
        tikz += (f"\\node[layer, minimum width={layer_widths[i]}cm, "
                 f"minimum height={layer_h}cm] (layer{i}) at ({x},0) {{}};\n")
        for j in range(vis):
            y = j * 0.5 - (vis - 1) * 0.25
            fill = "blue!10" if 0 < i < n_layers - 1 else "white"
            tikz += f"\\node[neuron, fill={fill}] at ({x},{y:.2f}) {{}};\n"
        x += layer_widths[i] + 1.2
    for i in range(n_layers - 1):
        x1, x2 = x_offsets[i], x_offsets[i + 1]
        tikz += f"% Connections layer {i+1} -> {i+2}\n"
        tikz += f"\\draw[arrows, opacity=0.3] ({x1 + 0.2}, -0.5) -- ({x2 - 0.2}, 0.5);\n"
        tikz += f"\\draw[arrows, opacity=0.3] ({x1 + 0.2}, 0.5) -- ({x2 - 0.2}, -0.5);\n"
    for i, (n, _t) in enumerate(layers):
        tikz += (f"\\node[font=\\footnotesize, below] "
                 f"at ({x_offsets[i]},-{max(n*0.3, 1.2)}) {{{n}}};\n")
    tikz += "\\end{tikzpicture}\n"
    return tikz


def _render_typed_blocks(layers: list, label: str, activation: str) -> str:
    """Draw colored nnblocks by layer type (PlotNeuralNet style), closer to a real architecture than per-dot."""
    n = len(layers)
    block_w = 1.2
    gap = 1.0
    xs = [i * (block_w + gap) for i in range(n)]
    lines = [
        f"% Neural Network Diagram: {label}",
        "% Generated by neural-net-draw skill (method=typed-blocks)",
        f"% activation={activation}  (recorded only; blocks show layer type)",
        "% Compile with: pdflatex + pgfplots + tikz",
        "\\def\\nnblock#1{\\draw (0,0) rectangle (1.2,0.9) node[align=center, font=\\scriptsize] {#1};}",
        "\\begin{tikzpicture}[>={Stealth}, every node/.style={font=\\footnotesize}]",
    ]
    for i, (w, t) in enumerate(layers):
        abbr, color = LAYER_TYPES[t]
        lines.append(f"% Layer {i+1}: {w} {t}")
        lines.append(
            f"\\node[draw, fill={color}, minimum width={block_w}cm, "
            f"minimum height=0.9cm, align=center] "
            f"at ({xs[i]+block_w/2},0.45) {{{abbr}}};\n"
            f"\\node[below, font=\\scriptsize] at ({xs[i]+block_w/2},0) "
            f"{{{w}}};\n")
    for i in range(n - 1):
        x1 = xs[i] + block_w
        x2 = xs[i + 1]
        lines.append(
            f"\\draw[{'>=Stealth'}, opacity=0.6] ({x1},0.45) -- node[above, font=\\tiny]{{}} ({x2},0.45);\n")
    lines.append("\\end{tikzpicture}\n")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Neural network diagram (TikZ)")
    parser.add_argument("--layers", required=True,
                        help="Comma-separated; bare int (old) or 'width:type' "
                             "(types: input,conv,pool,residual,linear,fc,attention,dropout,output)")
    parser.add_argument("--label", default="Model")
    parser.add_argument("--activation", default="relu")
    parser.add_argument("--style", default="auto",
                        choices=["auto", "per-neuron", "typed-blocks"],
                        help="auto=typed-blocks when types present, else per-neuron (default)")
    parser.add_argument("--output", help="Output .tex file (default /tmp/nn_model.tex)")
    args = parser.parse_args()
    result = draw_nn(args.layers, args.label, args.activation, args.output, args.style)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    sys.exit(main())
