#!/usr/bin/env python3
"""Neural Net Drawer — 生成神经网络结构图 (LaTeX TikZ)。

学习自: PlotNeuralNet (25k stars)
输出: 可直接编译的 TikZ 代码

用法:
  python3 neural_net_draw.py --layers "784,512,256,10,1" --label "CNN+MLP"
  python3 neural_net_draw.py --layers "64,128,64,10" --activation relu
"""
import argparse
import json
import sys
from pathlib import Path


def draw_nn(layers: list, label: str = "Model", activation: str = "relu",
             output: str = None) -> dict:
    """Generate TikZ neural network diagram."""
    out = Path(output or "/tmp/nn_model.tex")

    n_layers = len(layers)
    layer_widths = [max(0.5, 4.0 / max(n_layers, 2)) for _ in layers]

    tikz = f"""% Neural Network Diagram: {label}
% Generated by neural-net-draw skill
% Compile with: pdflatex + pgfplots
\\begin{{tikzpicture}}[
  neuron/.style={{circle, draw, black!80!white, minimum size=0.4cm, inner sep=0pt}},
  layer/.style={{draw, minimum height=1.5cm, opacity=0.3, fill=gray!10}},
  arrows/.style={{-{'>'}}}
]

"""
    x_offsets = []
    x = 0
    for i, (n_nodes, lw) in enumerate(zip(layers, layer_widths)):
        x_offsets.append(x)
        layer_h = max(n_nodes * 0.6, 0.8)

        # Layer bracket
        tikz += f"% Layer {i+1}: {n_nodes} nodes\n"
        tikz += f"\\node[layer, minimum width={lw}cm, minimum height={layer_h}cm] (layer{i}) at ({x},0) {{}};\n"

        # Nodes
        for j in range(min(n_nodes, 10)):  # Cap at 10 visible nodes
            y = j * 0.5 - (min(n_nodes, 10) - 1) * 0.25
            fill = "blue!10" if 0 < i < n_layers - 1 else "white"
            tikz += f"\\node[neuron, fill={fill}] at ({x},{y}) {{}};\n"

        x += lw + 1.2

    # Arrows between layers
    for i in range(n_layers - 1):
        x1 = x_offsets[i]
        x2 = x_offsets[i + 1]
        tikz += f"% Connections layer {i+1} -> {i+2}\n"
        tikz += f"\\draw[arrows, opacity=0.3] ({x1 + 0.2}, -0.5) -- ({x2 - 0.2}, 0.5);\n"
        tikz += f"\\draw[arrows, opacity=0.3] ({x1 + 0.2}, 0.5) -- ({x2 - 0.2}, -0.5);\n"

    # Labels
    for i, n in enumerate(layers):
        tikz += f"\\node[font=\\footnotesize, below] at ({x_offsets[i]},-{max(layers[i]*0.3, 1.2)}) {{{n}}};\n"

    tikz += f"""\\end{{tikzpicture}}
"""
    out.write_text(tikz, encoding="utf-8")

    return {
        "output": str(out),
        "label": label,
        "layers": layers,
        "activation": activation,
        "n_params_est": _estimate_params(layers),
        "compilable": True,
        "note": "Requires pgfplots in LaTeX preamble",
    }


def _estimate_params(layers: list) -> str:
    """Rough parameter count estimate."""
    total = 0
    for i in range(len(layers) - 1):
        total += layers[i] * layers[i + 1] + layers[i + 1]
    if total > 1_000_000:
        return f"~{total/1_000_000:.1f}M"
    elif total > 1000:
        return f"~{total/1000:.1f}K"
    return f"{total}"


def main():
    parser = argparse.ArgumentParser(description="Neural network diagram (TikZ)")
    parser.add_argument("--layers", required=True, help="Comma-separated layer sizes")
    parser.add_argument("--label", default="Model")
    parser.add_argument("--activation", default="relu")
    parser.add_argument("--output", help="Output .tex file")
    args = parser.parse_args()

    layers = [int(x) for x in args.layers.split(",")]
    result = draw_nn(layers, args.label, args.activation, args.output)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    sys.exit(main())
