# -*- coding: utf-8 -*-
"""audio / music / image · 真实图片 + 真实可运行程序交付物。
（video 域已单独 video_task；此文件给 image-studio 出真实图片 + 可运行小工具。）"""
SKILL = "image-studio"
DOMAIN = "image"


def run(ctx, ffmpeg):
    ctx.think(
        "image-studio（图片生成/3D）。本机无 GPU 无法跑 diffusion；"
        "用 PIL 生成一张真实「海报级」图片（电影感暗色 + 渐变 + 标题排版），"
        "并产出一个**可运行的 Python 小工具** img_util.py（给任意图加暗色电影感滤镜），"
        "跑一遍验证可运行。"
    )
    from PIL import Image, ImageDraw, ImageFilter, ImageEnhance
    import os, math
    W, H = 1280, 720
    img = Image.new("RGB", (W, H), (10, 12, 18))
    d = ImageDraw.Draw(img)
    # 电影感渐变天空
    for y in range(H):
        t = y / H
        r = int(12 + t * 40)
        g = int(10 + t * 18)
        b = int(24 + (1 - t) * 70)
        d.line([(0, y), (W, y)], fill=(r, g, b))
    # 山体剪影（两层）
    for layer, (base, amp, col) in enumerate([(420, 90, (18, 20, 30)), (480, 50, (30, 34, 48))]):
        pts = [(0, H)]
        for x in range(0, W + 1, 8):
            h = base - (math.sin(x * 0.004 + layer) * amp + math.sin(x * 0.013) * amp * 0.4)
            pts.append((x, h))
        pts.append((W, H))
        d.polygon(pts, fill=col)
    # 标题排版
    d.text((80, 240), "NIGHTFALL", fill=(240, 244, 255), font_size=96)
    d.text((84, 360), "a cinematic concept frame · generated by image-studio", fill=(150, 160, 180), font_size=24)
    img = img.filter(ImageFilter.GaussianBlur(1))
    img = ImageEnhance.Contrast(img).enhance(1.15)
    out = os.path.join(ctx.d, "postframe.png")
    img.save(out)
    ctx.think(f"海报图 {out} ({os.path.getsize(out)//1024} KB)")

    # 可运行小工具
    tool = os.path.join(ctx.d, "img_util.py")
    with open(tool, "w", encoding="utf-8") as fh:
        fh.write(
            "from PIL import Image, ImageEnhance\n"
            "import sys\n"
            "def cinematic(p): im=Image.open(p); im=ImageEnhance.Contrast(im).enhance(1.2); "
            "im=ImageEnhance.Color(im).enhance(0.6); im.save(p+'.moody.jpg'); print('done',p+'.moody.jpg')\n"
            "if __name__=='__main__':\n    cinematic(sys.argv[1])\n"
        )
    r = ctx.run("python", [tool, out])
    if r and r.returncode == 0:
        ctx.think(f"img_util.py 可运行，产出 {out}.moody.jpg")
        ctx.result("pass", f"真实图片 {W}x{H} + 可运行工具 img_util.py（跑出 .moody.jpg）")
    else:
        ctx.problem("img_util.py 运行失败")
        ctx.result("warn", "图片已生成，但可运行工具验证失败")
    ctx.better("接 ImageGen / diffusion（有 GPU 环境）可出真设计稿；本机用 PIL 电影感滤镜替代并记录。")


if __name__ == "__main__":
    from full_skill_test import Recorder, get_ffmpeg, ARTIFACTS
    import os
    os.makedirs(ARTIFACTS, exist_ok=True)
    c = Recorder(SKILL, DOMAIN)
    run(c, get_ffmpeg())
    c.dump()
